import pandas as pd
import numpy as np
import logging

def calculate_rsi(series: pd.Series, period: int = 14) -> pd.Series:
    """
    Calculates the Relative Strength Index (RSI) using vectorized pandas operations.
    
    Args:
        series (pd.Series): Price series.
        period (int): Lookback period.
        
    Returns:
        pd.Series: RSI values (0-100).
    """
    delta = series.diff()
    
    # Separate gains and losses
    gain = (delta.where(delta > 0, 0)).fillna(0)
    loss = (-delta.where(delta < 0, 0)).fillna(0)
    
    # Calculate Exponential Moving Average (Wilder's Smoothing)
    avg_gain = gain.ewm(com=period - 1, min_periods=period).mean()
    avg_loss = loss.ewm(com=period - 1, min_periods=period).mean()
    
    # Calculate RS and RSI
    rs = avg_gain / avg_loss
    rsi = 100 - (100 / (1 + rs))
    
    return rsi

def add_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Generates technical and fundamental features for the ML model.
    All calculations are vectorized for performance.
    
    Args:
        df (pd.DataFrame): Dataframe with 'price', 'volume', 'temperature'.
        
    Returns:
        pd.DataFrame: Dataframe with added feature columns.
    """
    logging.info("Generating feature set...")
    
    df = df.copy()
    
    # --- 1. Target & Stationarity ---
    # Log Returns: The primary metric for volatility and prediction targets
    df['returns'] = np.log(df['price'] / df['price'].shift(1))
    
    # --- 2. Trend Indicators ---
    # We use ratios (Price / SMA) to make the feature stationary
    df['sma_20'] = df['price'].rolling(window=20).mean()
    df['sma_50'] = df['price'].rolling(window=50).mean()
    
    df['dist_sma_20'] = df['price'] / df['sma_20'] - 1
    df['dist_sma_50'] = df['price'] / df['sma_50'] - 1
    
    # --- 3. Momentum ---
    df['rsi'] = calculate_rsi(df['price'], period=14)
    
    # --- 4. Volatility ---
    # 20-day rolling standard deviation of returns
    df['volatility'] = df['returns'].rolling(window=20).std()
    
    # --- 5. Fundamental (Weather) ---
    # Temperature Anomaly: Deviation from the 30-day rolling average temperature
    # (High deviation often correlates with energy demand spikes)
    df['temp_ma_30'] = df['temperature'].rolling(window=30).mean()
    df['temp_anomaly'] = df['temperature'] - df['temp_ma_30']
    
    # --- 6. Cleaning ---
    # Drop NaN values generated by rolling windows (the first 50 rows)
    df.dropna(inplace=True)
    
    logging.info(f"Feature engineering complete. Final shape: {df.shape}")
    return df